import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:testingterminal/provider/widget_checker_viewmodel.dart';
import 'package:testingterminal/studentlist/stdlist.dart';

class ProviderExample extends StatefulWidget {
  const ProviderExample({super.key});

  @override
  State<ProviderExample> createState() => _ProviderExampleState();
}

class _ProviderExampleState extends State<ProviderExample> {
  @override
  Widget build(BuildContext context) {
    debugPrint('build called');
    List<String> student = [
      "Liam Smith",
      "Noah Johnson",
      "Oliver Williams",
      "James Brown",
      "Elijah Jones",
      "William Garcia",
      "Henry Miller",
      "Lucas Davis",
      "Benjamin Rodriguez",
      "Theodore Martinez",
      "Mateo Hernandez",
      "Levi Lopez",
      "Sebastian Gonzalez",
      "Daniel Wilson",
      "Jack Anderson",
      "Alexander Thomas",
      "Owen Taylor",
      "Arlo Moore",
      "Samuel Jackson",
      "Joseph Martin",
      "John Lee",
      "David Perez",
      "Wyatt Thompson",
      "Luke White",
      "Asher Harris",
      "Carter Sanchez",
      "Julian Clark",
      "Leo Ramirez",
      "Hudson Lewis",
      "Anthony Robinson",
      "Isaac Walker",
      "Gabriel Young",
      "Alfie Allen",
      "Lincoln King",
      "Thomas Wright",
      "Maverick Scott",
      "Logan Torres",
      "Jaxon Nguyen",
      "Nathan Hill",
      "Ezra Flores",
      "Elias Green",
      "Andrew Adams",
      "Charles Nelson",
      "Caleb Baker",
      "Josiah Hall",
      "Isaiah Rivera",
      "Thomas Campbell",
      "Eli Mitchell",
      "Aaron Carter",
      "Ryan Roberts",
      "Adrian Gomez",
      "Miles Phillips",
      "Nolan Evans",
      "Christian Turner",
      "Brooks Diaz",
      "Christopher Parker",
      "Cooper Cruz",
      "Jonathan Edwards",
      "Axel Collins",
      "Parker Reyes",
      "Roman Stewart",
      "Santiago Morris",
      "Ian Morales",
      "Jordan Murphy",
      "Hunter Cook",
      "Xavier Rogers",
      "Kai Gutierrez",
      "Dominic Ortiz",
      "Jose Morgan",
      "Ezekiel Cooper",
      "Adam Peterson",
      "Jace Bailey",
      "Jameson Reed",
      "Evan Kelly",
      "Max Howard",
      "Grayson Ramos",
      "Bryson Kim",
      "Damian Cox",
      "Silas Ward",
      "Rowan Richardson",
      "Luka Watson",
      "Amir Brooks",
      "Vincent Chao",
      "Everett Wood",
      "Bennett James",
      "Ryker Bennett",
      "Micah Gray",
      "August Mendoza",
      "Emmett Ruiz",
      "Kai Hughes",
      "Beau Price",
      "Angel Alvarez",
      "Tristan Castillo",
      "Milo Sanders",
      "Walker Patel",
      "Kevin Myers",
      "Zachary Long",
      "Silas Ross",
      "Jasper Foster",
      "Declan Jimenez",
      "Beckett Powell",
      "Finn Jenkins",
      "Zion Perry",
      "Adriel Russell",
      "Arthur Sullivan",
      "Kyrie Bell",
      "Casper Coleman",
      "Tatum Butler",
      "Zander Henderson",
      "Gael Barnes",
      "Cade Gonzales",
      "Kellan Fisher",
      "Riley Vasquez",
      "River Simmons",
      "Augustine Romero",
      "Knox Jordan",
      "Beckham Patterson",
      "Atlas Alexander",
      "Leon Marshall",
      "Major Lowe",
      "Iker Bryan",
      "Jett Larson",
      "Kobe Mendez",
      "Malachi Freeman",
      "Nasir Wells",
      "Omari Webb",
      "Pierce Simpson",
      "Quinton Stevens",
      "Reed Tucker",
      "Sincere Porter",
      "Talon Hunter",
      "Uriel Hicks",
      "Vance Crawford",
      "Wilder Henry",
      "Xzavier Boyd",
      "Yosef Mason",
      "Zayn Morales",
      "Alaric Kennedy",
      "Bodie Warren",
      "Callum Dixon",
      "Dax Ramos",
      "Enoch Reyes",
      "Forrest Burns",
      "Gideon Gordon",
      "Harlan Shaw",
      "Isaias Holmes",
      "Jenson Rice",
      "Kasen Robertson",
      "Lachlan Hunt",
      "Miller Black",
      "Nico Daniels",
      "Otto Palmer",
      "Phineas Mills",
      "Quinn Nichols",
      "Rocco Grant",
      "Sutton Knight",
      "Thatcher Ferguson",
      "Ulysses Rose",
      "Vihaan Stone",
      "Wells Hawkins",
      "Xander Dunn",
      "Yisroel Perkins",
      "Zev Hudson",
      "Alistair Spencer",
      "Blaise Gardner",
      "Crosby Stephens",
      "Dante Payne",
      "Ellis Pierce",
      "Fisher Berry",
      "Grey Matthews",
      "Hayes Arnold",
      "Idris Wagner",
      "Judah Willis",
      "Koa Ray",
      "Ledger Watkins",
      "Murphy Olson",
      "Noel Chapman",
      "Onyx Grant",
      "Pax Meyer",
      "Ridge Bishop",
      "Shepherd Fox",
      "Titan Greene",
      "Urban Bush",
      "Valor Hammett",
      "Wolfgang Love",
      "Xander Best",
      "Yosef Cain",
      "Zaire Adkins",
      "Axton Foster",
      "Bane Wyatt",
      "Castiel George",
      "Dash Hardin",
      "Eamon Jennings",
      "Falcon Holloway",
      "Guye Lara",
      "Huxley Vance",
      "Ira Booth",
      "Jericho Orr",
      "Kyson Abbott",
      "Lars Eaton",
      "Magnus Knapp",
      "Neo Moses",
      "Odin Pittman",
      "Pike Poole",
      "Quest Rollins",
      "Raine Small",
      "Stellan Stout",
      "True Tanner",
      "Vonn Walls",
      "Zeke York",
    ];

    return Scaffold(
      appBar: AppBar(title: Text('provider Paractices')),
      body: Column(
        children: [
          SizedBox(
            height: 700,
            child: ListView.builder(
              itemCount: student.length,
              itemBuilder: (context, index) => ListTile(
                leading: CircleAvatar(child: Icon(Icons.person)),
                title: Text(student[index]),
                trailing: Consumer<IconButtonProvider>(
                  builder: (context, viewmodel, child) => IconButton(
                    onPressed: () {
                      viewmodel.toggleFavorite(student[index]);
                    },
                    icon: Icon(
                      viewmodel.isfavourite.contains(student[index])
                          ? Icons.favorite
                          : Icons.favorite_border_outlined,
                      color: Colors.red,
                    ),
                  ),
                ),
              ),
            ),
          ),
          // _examples1(),
        ],
      ),
    );
  }

  // Center _examples1() {
  //   return Center(
  //     child: Consumer<IconButtonProvider>(
  //       builder: (context, viemodel, child) => IconButton(
  //         onPressed: () {
  //           viemodel.favoriteIconChange();
  //         },
  //         icon: Icon(
  //           viemodel.isfavourite ? Icons.favorite : Icons.favorite_border,
  //           size: 50,
  //           color: Colors.red,
  //         ),
  //       ),
  //     ),
  //   );
  // }
}
